# -*- coding: utf-8 -*-
"""Np,Pd,Plt(Mini Project1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3azvNGD6QJIFjsQSuXEiE4sgAnnzpNG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


data=pd.read_csv("/content/students.csv")
print(data)

print(data.head(5))

print(data.tail(5))

print(data.info())

#4. Find average marks in each subject.
print("Math average : ",data["Math"].mean())
print("Science average : ",data["Science"].mean())
print("Science average : ",data["Science"].mean())

#5.
data["Total"]=data["Math"]+data["Science"]+data["English"]
data["Percentage"]=data["Total_Marks"]/3
print(data[['Name','Total','Percentage']])

#6.
data.loc[(data["Percentage"]>=65),"Grade"]="C"
data.loc[(data["Percentage"]>=70),"Grade"]="B"
data.loc[(data["Percentage"]>=80),"Grade"]="A"
data.loc[(data["Percentage"]<65),"Grade"]="F"
print(data)

#7. Find topper student.

topper=data[data['Percentage']==data['Percentage'].max()]
print(topper)

data["Total_Marks"] = data["Math"] + data["Science"] + data["English"]
data["Percentage"] = data["Total_Marks"] / 3
#8.
low_attendance=data[data['Attendance']==data['Attendance'].min()]
print(low_attendance)

#9.
above_75=data[data['Percentage']>75]
print(above_75)

#10.
female_A=data[(data['Gender']=='Female') & (data['Grade']=='A')]
print(female_A)

#11.
gp=data.groupby('Gender')['Percentage'].mean()
print(gp)

#12.
gp=data.groupby('Month')['Attendance'].mean()
print(gp)

#13.
gp=data[["Math","Science","English"]].mean()
print(gp)

plt.bar(gp.index,gp.values)
plt.xlabel("Subjects")
plt.ylabel("Avg Marks")
plt.title("Subjects wise avg marks")
plt.show()

#14.
#data['Total']=data['Math']
plt.hist(data["Percentage"])
plt.xlabel("Percentage")
plt.ylabel("Frequency")
plt.title("Percentage Distribution")
plt.show()

#15.

gp=data["Grade"].value_counts()
print(gp)

plt.pie(gp.values,labels=gp.index,autopct="%1.1f%%")
plt.title("Grade Distribution")
plt.show()

#16.
plt.scatter(data["Attendance"],data["Percentage"])
plt.xlabel("Attendance")
plt.ylabel("Percentage")
plt.title("Attendance vs Percentage")

plt.show()

#17.
plt.boxplot([data['Math'],data['Science'],data['English']])
plt.xticks([1,2,3],['Math','Science','English'])
plt.title("Boxplot of marks")
plt.show()

#18.

arr=data["Percentage"].values
print("Mean :",np.mean(arr))
print("Median :",np.median(arr))
print("Standard Deviation :",np.std(arr))

#19.
data["Bonus_Marks"]=np.random.randint(1,6,size=len(data))
print(data[["Name","Bonus_Marks"]])

#20.  Export topper student data into a new CSV file
import pandas as pd

# Read existing CSV file
data = pd.read_csv("/content/students.csv")

# Calculate Total Marks and Percentage (as done in previous cells)
data["Total_Marks"] = data["Math"] + data["Science"] + data["English"]
data["Percentage"] = data["Total_Marks"] / 3

# Filter topper students based on Percentage
topper_students = data[data["Percentage"] > 80]

# Export to new CSV file
topper_students.to_csv("toppers.csv", index=False)

print("Topper students exported successfully!")

data=pd.read_csv("/content/toppers.csv")
print(data)